<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "store_locator"
 *
 * Auto generated by Extension Builder 2013-02-26
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Store Locator',
	'description' => 'This store locator display all the store information on a Google Map',
	'category' => 'plugin',
	'author' => 'Julian Kleinhans',
	'author_email' => 'julian.kleinhans@aijko.de',
	'author_company' => 'aijko GmbH',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.0',
			'fluid' => '6.0',
			'typo3' => '6.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>